import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css';
import Nav from './components/Nav'
import Footer from './components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'HT-Garments',
  description: 'Generated by M.farhan',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Conditionally render ClerkProvider */}
        {process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ? (
          <ClerkProvider 
            publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
            appearance={{
              baseTheme: undefined
            }}
          >
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              {/* Your header content */}
            </header>
            <Nav />
            {children}
            <Footer />
          </ClerkProvider>
        ) : (
          // During build or when key is missing, render without Clerk
          <>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              {/* Your header content */}
            </header>
            <Nav />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  )
}